#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#define ACCESSIBILITY_CONTROL_CHANNEL 11
#define ACCESSIBILITY_RIGHT_CLICK_CHANNEL 9

#define ACCESSIBILITY_DEBOUNCE_POLLS 3

#define ACCESSIBILITY_TRIPLE_TAP_COUNT 3
#define ACCESSIBILITY_TAP_MAX_INTERVAL_MS 800
#define ACCESSIBILITY_LONG_PRESS_MS 2500
#define ACCESSIBILITY_LONG_PRESS_RELEASE_GRACE_MS 900

#define ACCESSIBILITY_CTRL_HOLD_MS 700
#define ACCESSIBILITY_ALT_KEY_PERIOD_MS 600
#define ACCESSIBILITY_ALT_KEY_HOLD_MS 800

#define ACCESSIBILITY_HID_KEY_A 0x04
#define ACCESSIBILITY_HID_KEY_D 0x07
#define ACCESSIBILITY_HID_KEY_LEFT_CTRL 0xe0

#ifdef __cplusplus
}
#endif
